services:

  backend:
    build: ./backend
    container_name: maison_aura_backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: maison_aura_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  stripe-cli:
    image: stripe/strip-cli:latest
    container_name: maison_aura_stripe
    command: listen --forward-to localhost:5000/api/webhook
    environment:
      STRIPE_API_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_DEVICE_NAME: maison-aura-local
    depends_on:
    - backend
    restart: unless-stopped
