apiVersion: v1
kind: Service
metadata:
  name: maison-aura-backend
  namespace: maison-aura
spec:
  selector:
    app: maison-aura-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
