apiVersion: v1
kind: Service
metadata:
  name: maison-aura-frontend
  namespace: maison-aura
spec:
  selector:
    app: maison-aura-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
