apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: maison-aura-secrets
  namespace: maison-aura
spec:
  provider: azure
  secretObjects:
    - secretName: maison-aura-secrets
      type: Opaque
      data:
        - objectName: DB-USER
          key: DB_USER
        - objectName: DB-PASSWORD
          key: DB_PASSWORD
        - objectName: DB-HOST
          key: DB_HOST
        - objectName: DB-PORT
          key: DB_PORT
        - objectName: DB-NAME
          key: DB_NAME
        - objectName: JWT-SECRET
          key: JWT_SECRET
        - objectName: STRIPE-SECRET-KEY
          key: STRIPE_SECRET_KEY
        - objectName: STRIPE-WEBHOOK-SECRET
          key: STRIPE_WEBHOOK_SECRET
        - objectName: CORS-ORIGIN
          key: CORS_ORIGIN
  parameters:
    usePodIdentity: "false"
    clientID: ""
    keyvaultName: ""
    cloudName: ""
    objects: |
      array:
        - |
          objectName: DB-USER
          objectType: secret
        - |
          objectName: DB-PASSWORD
          objectType: secret
        - |
          objectName: DB-HOST
          objectType: secret
        - |
          objectName: DB-PORT
          objectType: secret
        - |
          objectName: DB-NAME
          objectType: secret
        - |
          objectName: JWT-SECRET
          objectType: secret
        - |
          objectName: STRIPE-SECRET-KEY
          objectType: secret
        - |
          objectName: STRIPE-WEBHOOK-SECRET
          objectType: secret
        - |
          objectName: CORS-ORIGIN
          objectType: secret
    tenantId: ""
