apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "cc572bd4-a95e-4595-94ff-6bb20693a8e3"   # aks_csi_identity_client_id output
    keyvaultName: "maisonaura-kv2"
    tenantId: "6ef653bc-0627-441c-900e-6b1dd1105de3"
    objects: |
      array:
        - |
          objectName: DB-USER
          objectType: secret
        - |
          objectName: DB-PASSWORD
          objectType: secret
        - |
          objectName: DB-HOST
          objectType: secret
        - |
          objectName: DB-PORT
          objectType: secret
        - |
          objectName: DB-NAME
          objectType: secret
        - |
          objectName: JWT-SECRET
          objectType: secret
        - |
          objectName: CORS-ORIGIN
          objectType: secret
        - |
          objectName: STRIPE-SECRET-KEY
          objectType: secret
        - |
          objectName: STRIPE-WEBHOOK-SECRET
          objectType: secret
  secretObjects:
    - secretName: db-secret
      type: Opaque
      data:
        - objectName: DB-USER
          key: DB_USER
        - objectName: DB-PASSWORD
          key: DB_PASSWORD
        - objectName: DB-HOST
          key: DB_HOST
        - objectName: DB-PORT
          key: DB_PORT
        - objectName: DB-NAME
          key: DB_NAME
    - secretName: app-secret
      type: Opaque
      data:
        - objectName: JWT-SECRET
          key: JWT_SECRET
        - objectName: CORS-ORIGIN
          key: CORS_ORIGIN
    - secretName: stripe-secret
      type: Opaque
      data:
        - objectName: STRIPE-SECRET-KEY
          key: STRIPE_SECRET_KEY
        - objectName: STRIPE-WEBHOOK-SECRET
          key: STRIPE_WEBHOOK_SECRET
